### ISSUE TITLE
"!=" in code fences automatically become to "≠"

### ISSUE THREAD

**Issue by Misoto22** [liangjingkanji/DrakeTyporaTheme#93] opened 2022-07-09 05:56 UTC
### 描述问题
"!=" in code fences automatically become to "≠"

### 期望结果
"!=" in code fences stays "!="

### 截图
<img width="226" alt="image" src="https://user-images.githubusercontent.com/61451263/178093619-124fefa6-7e97-48f6-80b6-687b6e531f81.png">

### 系统 (建议使用最新Typora版本)
 - OS                            MacOS
 - Theme                     Drake Vue
 - Typora Version       1.3.7 (6424)

**Comment by liangjingkanji** [comment] 2022-07-09 05:57
Duplicate of #75

**Comment by liangjingkanji** [comment] 2022-07-09 16:34
If solved please close the issue

**Closed** 2022-07-09 21:36 UTC
